import React,{useEffect} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FirebaseAuth from '../components/auth/FirebaseAuth'
import {useUser} from '../firebase/useUser'

// import firebase from '../firebase/initFirebase'

export default function Home() {
  // useEffect(() => {
  //   //Init database, init firestore, create 10 new projects
  //   createMultipleProjects(getFirestore(initFirebase()))
  // },[]);
  
  const {user,logout}=useUser()
  useEffect(() => {
    
    (console.log(user))
  }, [user]);
  return (
    <div className={styles.container}>
      {console.log(user)}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>InvestInYou</a>
        </h1>

        <p className={styles.description}>
          Get started by with
          {/* <code className={styles.code}>pages/index.js</code> */}
        </p>
        <FirebaseAuth />
                
        </main>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
