import { useUser } from "../firebase/useUser";
import { userHoldings } from "../backend/user";
import { userDetails } from "../backend/user";
import AppBarComponent from "../components/AppBarComponent";
import { useState, useEffect } from "react";
import Link from "next/link";
import FooterComponent from "../components/FooterComponent";
import Head from "next/head";
import { Button, Skeleton } from "@mui/material";
import Loader from "../components/Loader";

function Portfolio() {
  const { user, logout } = useUser();
  let i = 0;
  // console.log(user.email)
  const email = user ? user.email : "sample";
  const { userData } = userDetails(email);
  const [holdings, setHoldings] = useState();
  useEffect(async () => {
    if (userData) {
      // console.log(userData.ref.id);
      setHoldings(await userHoldings(userData.ref));
    }
  }, [userData]);
  useEffect(() => {
    console.log(holdings);
  }, [holdings]);
  // async function signOut(){
  //   return logout;
  // }
  if (user && userData)
    return (
      <>
        <Head>
          <title>InvestInYou | Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AppBarComponent path={"/dashboard"} pathname={"Dashboard"} />
        <br />
        {user.profilePic ? (
          <img
            src={user.profilePic}
            style={{
              display: "block",
              marginTop: "60px",
              borderRadius: "100%",
              marginLeft: "auto",
              marginRight: "auto",
            }}
          />
        ) : (
          <Skeleton
            animation="wave"
            variant="circular"
            width={80}
            height={80}
            style={{
              display: "block",
              marginTop: "60px",
              borderRadius: "100%",
              marginLeft: "auto",
              marginRight: "auto",
            }}
          />
        )}
        <h1 style={{ textAlign: "center" }}>{user ? user.name : ""}</h1>
        <Button
          style={{ marginLeft: "auto", marginRight: "auto", display: "block" }}
          onClick={async () => {
            await logout();
          }}
        >
          Logout
        </Button>

        {userData ? (
          <h4 style={{ textAlign: "center" }}>
            Credit: ₹{userData.data.credit}
          </h4>
        ) : (
          ""
        )}
        {console.log(holdings)}
        {holdings && holdings[0]
          ? holdings.map((holding) => {
              return (
                <div key={i++} style={{ textAlign: "center" }}>
                  <Link
                    href={{
                      pathname: "/" + holding.assetName,
                      query: {
                        assetRef: holding.assetRef.id,
                      },
                    }}
                    as={`/${holding.assetRef.id}`}
                  >
                    <h3>Asset: {holding.assetName}</h3>
                  </Link>
                  {/* {console.log(holding.assetRef.id)} */}
                  <Link
                    href={{
                      pathname:
                        "/" + holding.assetName + "/" + holding.projectName,
                      query: {
                        projectRef: holding.projectRef.id,
                        assetRef: holding.assetRef.id,
                      },
                    }}
                    as={`/${holding.assetRef.id}/${holding.projectRef.id}`}
                  >
                    <h3>Project: {holding.projectName}</h3>
                  </Link>
                  <h3>quantity: {holding.quantity}</h3>
                </div>
              );
            })
          : ""}
        {/* <div style={{display:"block",paddingLeft:"auto",paddingRight:"auto"}}> */}
        {/* </div> */}
        <FooterComponent />
      </>
    );
  else return <Loader />;
}

export default Portfolio;
